---
title: ': A Wealth of Data'
output: pdf_document
Author: 
---
```{r}
library(tidyverse)
library(stringr)
library(lubridate)
```




```{r}
library(readr)

setwd('~/Desktop/Problem_C_Data')

hair_dryer <- read_tsv(file="hair_dryer.tsv")
microwave <- read_tsv(file="microwave.tsv")
pacifier <- read_tsv(file="pacifier.tsv")
```
Cleaning

```{r}
cleaned_hair_dryer= hair_dryer %>% filter(str_detect(tolower(product_title), "dryer"))
cleaned_microwave= microwave %>% filter(str_detect(tolower(product_title), "microwave"))
cleaned_pacifier= pacifier %>% filter(str_detect(tolower(product_title), "pacifier"))
```

```{r}
write.csv(cleaned_hair_dryer,"cleaned_hair_dryer.csv")
write.csv(cleaned_microwave,"cleaned_microwave.csv")
write.csv(cleaned_pacifier,"cleaned_pacifier.csv")
```

product rating by time
```{r}
some = mdy(microwave$review_date)
as_tibble(year(some), month(some), day(some))
cleaned_microwave= cleaned_microwave %>% mutate(year= lubridate::year(mdy(review_date)),
                     month= lubridate::month(mdy(review_date)),
                     day=lubridate::day(mdy(review_date)))

cleaned_hair_dryer= cleaned_hair_dryer %>% mutate(year= lubridate::year(mdy(review_date)),
                     month= lubridate::month(mdy(review_date)),
                     day=lubridate::day(mdy(review_date)))

cleaned_pacifier= cleaned_pacifier %>% mutate(year= lubridate::year(mdy(review_date)),
                     month= lubridate::month(mdy(review_date)),
                     day=lubridate::day(mdy(review_date)))

```


```{r}

cleaned_microwave %>% filter(product_parent==423421857)%>% filter(year==2015) %>% filter(month==7)%>%  ggplot() +geom_point(mapping=aes(x=review_date,y= star_rating))


geom_smooth(data=subset(copyKVClimate, year ==1950))+geom_smooth(data=subset(copyKVClimate, year == 2019))



  cleaned_microwave %>% filter(product_parent==423421857)%>% filter(year==2015)   %>% ggplot()+ geom_histogram(mapping=aes(x=star_rating, fill=as.factor(monnth)),position="dodge",binwidth=0.7) + scale_fill_manual(breaks=1:12, values=c())
  
  
  
product1= cleaned_microwave %>% filter(product_parent==423421857)
ggplot(data=product1, mapping=aes(x=as.factor(month),group=star_rating,  color=as.factor(star_rating))) + geom_line(stat="count")+geom_point(stat="count")+facet_wrap(product1$year)
```
 %>% ggplot(mapping=aes(x=month, y= count ), color=as.factor(star_rating))+ geom_line()
 
 
 ggplot(copyKVClimate,aes( month, TMIN, color=as.factor(year)))+geom_smooth(data=subset(copyKVClimate, year ==1950))+geom_smooth(data=subset(copyKVClimate, year == 2019))+ggtitle("Minimum Temperatures by Month")+ylab("Minimum Temperature")+xlab("Month")

```{r}
clean_hair_dryer_scores <- read_csv("clean_hair_dryer_scores.csv")
clean_microwave_scores <- read_csv("clean_microwave_scores.csv")
clean_pacifier_scores <- read_csv("clean_pacifier_scores.csv")
hair_dryer_scores=merge(cleaned_hair_dryer,clean_hair_dryer_scores,by="review_id")
microwave_scores=merge(cleaned_microwave,clean_microwave_scores,by="review_id")
pacifier_scores=merge(cleaned_pacifier,clean_pacifier_scores,by="review_id")
```

